---
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    # Uses the user defined in .env
    user: ${JELLYFIN_USER}
    network_mode: 'host'
    volumes:
      - ${CONFIG_DIR}:/config
      - ${CACHE_DIR}:/cache
      - type: bind
        source: ${MEDIA_DIR}
        target: /media
        read_only: true

    restart: 'unless-stopped'
    # Optional - alternative address used for autodiscovery
    environment:
      - JELLYFIN_PublishedServerUrl=${JELLYFIN_URL}
